### ISSUE TITLE
feature/sign-up: Create sign-up functionality for users

### ISSUE THREAD

**Issue by aapeshave** [aapeshave/CloudBusters#10]
Design Signup flow 
Implement Signup flow
Design and Implement Signup Entity
Design and Implement MVC Layer

**Comment by aapeshave** [comment]
zala ka kaam @ameyutturkar ?

**Comment by ameyutturkar** [comment]
zala nalast time commit kela tevhach. db set up zala ki fakta db insert takaycha ahe. currently showing on the web page. but will discuss the parameters to input from user
